server:
  address: localhost
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/laundry24?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpw